### ISSUE TITLE
Publish clear and clearLine

### ISSUE THREAD

**Issue by Refefer** [jmillikin/haskell-ncurses#1]
Hi there,

I'm enjoying your library which is quite easy to use.  I see you've done some work to add clear and clearLine and was hoping you could publish it to cabal.

Thanks!

**Comment by jmillikin** [comment]
Sorry for the delay; I didn't see this issue in my dashboard.

Version 0.2.12 has been uploaded to Hackage, with `clear` and `clearLine` exported.
