### ISSUE TITLE
windowPosition x/y swapped

### ISSUE THREAD

**Issue by fredlebel** [jmillikin/haskell-ncurses#3]
windowPosition returns the x and y coordinates swapped.

**Comment by jmillikin** [comment]
Oh dear, this also applies to `windowSize` and `cursorPosition`. The docs all specify (row,column) but the code is in terms of (x,y).

Fixed in commit 7aa383e90b16f4a96cad07e3e4ae7ef5bbbbecc9; version 0.2.14 uploaded to Hackage.

Thank you for filing this bug!
